# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mason/workspace/slb_node/ourRDMA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mason/workspace/slb_node/ourRDMA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mason/workspace/slb_node/ourRDMA/CMakeFiles /home/mason/workspace/slb_node/ourRDMA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mason/workspace/slb_node/ourRDMA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rdma_server

# Build rule for target.
rdma_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdma_server
.PHONY : rdma_server

# fast build rule for target.
rdma_server/fast:
	$(MAKE) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/build
.PHONY : rdma_server/fast

#=============================================================================
# Target rules for targets named rdma_client_esg

# Build rule for target.
rdma_client_esg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdma_client_esg
.PHONY : rdma_client_esg

# fast build rule for target.
rdma_client_esg/fast:
	$(MAKE) -f CMakeFiles/rdma_client_esg.dir/build.make CMakeFiles/rdma_client_esg.dir/build
.PHONY : rdma_client_esg/fast

#=============================================================================
# Target rules for targets named rdma_client

# Build rule for target.
rdma_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdma_client
.PHONY : rdma_client

# fast build rule for target.
rdma_client/fast:
	$(MAKE) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/build
.PHONY : rdma_client/fast

#=============================================================================
# Target rules for targets named rdma_simple

# Build rule for target.
rdma_simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdma_simple
.PHONY : rdma_simple

# fast build rule for target.
rdma_simple/fast:
	$(MAKE) -f CMakeFiles/rdma_simple.dir/build.make CMakeFiles/rdma_simple.dir/build
.PHONY : rdma_simple/fast

src/rdma_client.o: src/rdma_client.cpp.o

.PHONY : src/rdma_client.o

# target to build an object file
src/rdma_client.cpp.o:
	$(MAKE) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/rdma_client.cpp.o
.PHONY : src/rdma_client.cpp.o

src/rdma_client.i: src/rdma_client.cpp.i

.PHONY : src/rdma_client.i

# target to preprocess a source file
src/rdma_client.cpp.i:
	$(MAKE) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/rdma_client.cpp.i
.PHONY : src/rdma_client.cpp.i

src/rdma_client.s: src/rdma_client.cpp.s

.PHONY : src/rdma_client.s

# target to generate assembly for a file
src/rdma_client.cpp.s:
	$(MAKE) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/rdma_client.cpp.s
.PHONY : src/rdma_client.cpp.s

src/rdma_client_esg.o: src/rdma_client_esg.cpp.o

.PHONY : src/rdma_client_esg.o

# target to build an object file
src/rdma_client_esg.cpp.o:
	$(MAKE) -f CMakeFiles/rdma_client_esg.dir/build.make CMakeFiles/rdma_client_esg.dir/src/rdma_client_esg.cpp.o
.PHONY : src/rdma_client_esg.cpp.o

src/rdma_client_esg.i: src/rdma_client_esg.cpp.i

.PHONY : src/rdma_client_esg.i

# target to preprocess a source file
src/rdma_client_esg.cpp.i:
	$(MAKE) -f CMakeFiles/rdma_client_esg.dir/build.make CMakeFiles/rdma_client_esg.dir/src/rdma_client_esg.cpp.i
.PHONY : src/rdma_client_esg.cpp.i

src/rdma_client_esg.s: src/rdma_client_esg.cpp.s

.PHONY : src/rdma_client_esg.s

# target to generate assembly for a file
src/rdma_client_esg.cpp.s:
	$(MAKE) -f CMakeFiles/rdma_client_esg.dir/build.make CMakeFiles/rdma_client_esg.dir/src/rdma_client_esg.cpp.s
.PHONY : src/rdma_client_esg.cpp.s

src/rdma_server.o: src/rdma_server.cpp.o

.PHONY : src/rdma_server.o

# target to build an object file
src/rdma_server.cpp.o:
	$(MAKE) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/rdma_server.cpp.o
.PHONY : src/rdma_server.cpp.o

src/rdma_server.i: src/rdma_server.cpp.i

.PHONY : src/rdma_server.i

# target to preprocess a source file
src/rdma_server.cpp.i:
	$(MAKE) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/rdma_server.cpp.i
.PHONY : src/rdma_server.cpp.i

src/rdma_server.s: src/rdma_server.cpp.s

.PHONY : src/rdma_server.s

# target to generate assembly for a file
src/rdma_server.cpp.s:
	$(MAKE) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/rdma_server.cpp.s
.PHONY : src/rdma_server.cpp.s

src/rdma_simple.o: src/rdma_simple.cpp.o

.PHONY : src/rdma_simple.o

# target to build an object file
src/rdma_simple.cpp.o:
	$(MAKE) -f CMakeFiles/rdma_simple.dir/build.make CMakeFiles/rdma_simple.dir/src/rdma_simple.cpp.o
.PHONY : src/rdma_simple.cpp.o

src/rdma_simple.i: src/rdma_simple.cpp.i

.PHONY : src/rdma_simple.i

# target to preprocess a source file
src/rdma_simple.cpp.i:
	$(MAKE) -f CMakeFiles/rdma_simple.dir/build.make CMakeFiles/rdma_simple.dir/src/rdma_simple.cpp.i
.PHONY : src/rdma_simple.cpp.i

src/rdma_simple.s: src/rdma_simple.cpp.s

.PHONY : src/rdma_simple.s

# target to generate assembly for a file
src/rdma_simple.cpp.s:
	$(MAKE) -f CMakeFiles/rdma_simple.dir/build.make CMakeFiles/rdma_simple.dir/src/rdma_simple.cpp.s
.PHONY : src/rdma_simple.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rdma_server"
	@echo "... rdma_client_esg"
	@echo "... rdma_client"
	@echo "... rdma_simple"
	@echo "... src/rdma_client.o"
	@echo "... src/rdma_client.i"
	@echo "... src/rdma_client.s"
	@echo "... src/rdma_client_esg.o"
	@echo "... src/rdma_client_esg.i"
	@echo "... src/rdma_client_esg.s"
	@echo "... src/rdma_server.o"
	@echo "... src/rdma_server.i"
	@echo "... src/rdma_server.s"
	@echo "... src/rdma_simple.o"
	@echo "... src/rdma_simple.i"
	@echo "... src/rdma_simple.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

